name: data_solaire
description: "Surveillance en temps réel du tracker solaire intelligent."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.5.0
  fl_chart: ^0.70.2
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  vector_math: ^2.2.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: assets/branding/app_icon.png
  web:
    generate: true
